name: dictionary
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - python-dotenv
  - ca-certificates
  - certifi
  - openssl
  - ipykernel
  - nbclient
  - pip
  - pip:
    - -r requirements.txt
