name: dictionary
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake
  - python-dotenv
  - ca-certificates
  - certifi
  - openssl
  - ipykernel
  - r-base
  - r-knitr
  - r-markdown
  - pip
  - pip:
    - -r requirements.txt
