name: Build duckdb database and archive

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true

      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt

      - name: Install duckdb
        uses: opt-nc/setup-duckdb-action@v1.0.9

      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Test installations
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          echo -n "snakemake: " && snakemake --version
          echo -n "python: " && python --version
          echo -n "duckdb: " && duckdb --version
          echo -n "quarto: " && quarto --version
          echo -n "mamba: " && micromamba --version
          pwd
          # snakemake --use-conda all -n
          micromamba info
            
